services:
  - type: web
    name: student-info
    env: python
    # Install deps, collect static files, run migrations
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    # Gunicorn start command (no "web:" prefix here)
    startCommand: gunicorn studentcrud.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: studentcrud.settings
      - key: SECRET_KEY
        value: c1v)(20r^-190@cfbjq@d7m65z=(5f#gq@ocwb8j8+ol+78u2)
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: student-info-eg0b.onrender.com
