# Generated by Django 5.2 on 2025-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
